name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --target rust-builder -t crates-regisstry-test .

      - name: Run tests in the Docker container
        run: docker run crates-regisstry-test cargo test
